--- #YAML:1.0
name:               WebService-IMDB
version:            0.04
abstract:           OO Perl interface to the Internet Movie Database imdb.com
author:
    - Christopher Key <cjk32@cam.ac.uk>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Cache::FileCache:     0
    Class::Accessor:      0
    DateTime:             0
    DateTime::Duration:   0
    DateTime::Format::Strptime:  0
    DateTime::Incomplete:  0
    File::Spec::Functions:  0
    JSON:                 0
    LWP::UserAgent:       0
    URI:                  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
